# Generated by Django 3.2.4 on 2021-08-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aries',
        ),
    ]
