# Generated by Django 3.2.4 on 2021-08-06 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profession', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='authors_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('sign', models.CharField(blank=True, choices=[('', '------'), ('овен', 'овен'), ('телец', 'телец'), ('близнаци', 'близнаци'), ('рак', 'рак'), ('лъв', 'лъв'), ('дева', 'дева'), ('везни', 'везни'), ('скорпион', 'скорпион'), ('стрелец', 'стрелец'), ('козирог', 'козирог'), ('водолей', 'водолей'), ('риби', 'риби')], max_length=20, null=True)),
                ('element', models.CharField(blank=True, choices=[('', '------'), ('огън', 'огън'), ('земя', 'земя'), ('въздух', 'въздух'), ('вода', 'вода')], max_length=15, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quotes_pics')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET('unknown'), to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=models.SET('unknown'), related_name='quotes', to='quotes.author')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.quote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
