# Generated by Django 3.2.4 on 2021-06-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profession', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sign', models.CharField(blank=True, choices=[('овен', 'овен'), ('телец', 'телец'), ('близнаци', 'близнаци'), ('рак', 'рак'), ('лъв', 'лъв'), ('дева', 'дева'), ('везни', 'везни'), ('скорпион', 'скорпион'), ('стрелец', 'стрелец'), ('козирог', 'козирог'), ('водолей', 'водолей'), ('риби', 'риби')], max_length=20, null=True)),
                ('element', models.CharField(choices=[('огън', 'огън'), ('земя', 'земя'), ('въздух', 'въздух'), ('вода', 'вода')], max_length=15)),
                ('author', models.ForeignKey(on_delete=models.SET('unknown'), to='quotes.author')),
            ],
        ),
    ]
