# Generated by Django 3.2.4 on 2021-07-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_rename_text_quote_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(on_delete=models.SET('unknown'), related_name='quotes', to='quotes.author'),
        ),
    ]
