# Generated by Django 3.2.4 on 2021-08-09 09:37

from django.db import migrations, models
import quote_generator.shared.validators


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20210809_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.TextField(validators=[quote_generator.shared.validators.has_quote]),
        ),
    ]
