# Generated by Django 3.2.4 on 2021-07-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_quote_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(blank=True, choices=[('овен', 'овен'), ('телец', 'телец'), ('близнаци', 'близнаци'), ('рак', 'рак'), ('лъв', 'лъв'), ('дева', 'дева'), ('везни', 'везни'), ('скорпион', 'скорпион'), ('стрелец', 'стрелец'), ('козирог', 'козирог'), ('водолей', 'водолей'), ('риби', 'риби')], max_length=20, null=True)),
            ],
        ),
    ]
