# Generated by Django 3.2.4 on 2021-08-09 10:39

from django.db import migrations, models
import quote_generator.shared.validators


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_quote_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.TextField(error_messages={'has_quote': 'Това поле е задължително'}, validators=[quote_generator.shared.validators.has_quote]),
        ),
    ]
