# Generated by Django 3.2.4 on 2021-07-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_myfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfilter',
            name='element',
            field=models.CharField(blank=True, choices=[('огън', 'огън'), ('земя', 'земя'), ('въздух', 'въздух'), ('вода', 'вода')], max_length=15, null=True),
        ),
    ]
