# Generated by Django 3.2.4 on 2021-07-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_myfilter_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
