# Generated by Django 3.2.4 on 2021-07-23 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0007_auto_20210717_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=models.SET('unknown'), to='auth.user'),
            preserve_default=False,
        ),
    ]
