# Generated by Django 3.2.4 on 2021-07-28 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_auto_20210728_2349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyFilter',
        ),
    ]
