# Generated by Django 3.2.4 on 2021-07-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_alter_quote_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='element',
            field=models.CharField(blank=True, choices=[('', '------'), ('огън', 'огън'), ('земя', 'земя'), ('въздух', 'въздух'), ('вода', 'вода')], max_length=15, null=True),
        ),
    ]
