# Generated by Django 3.2.4 on 2021-07-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210723_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme_profile',
            field=models.CharField(blank=True, choices=[('', '------'), ('0', 'шарено'), ('1', 'синьо небе'), ('2', 'зелено'), ('3', 'лилаво'), ('4', 'слънчево')], max_length=20, null=True),
        ),
    ]
