# Generated by Django 3.2.4 on 2021-09-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_zodiac_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='moon_sign',
            field=models.CharField(blank=True, choices=[('', '------'), ('овен', 'овен'), ('телец', 'телец'), ('близнаци', 'близнаци'), ('рак', 'рак'), ('лъв', 'лъв'), ('дева', 'дева'), ('везни', 'везни'), ('скорпион', 'скорпион'), ('стрелец', 'стрелец'), ('козирог', 'козирог'), ('водолей', 'водолей'), ('риби', 'риби')], max_length=20, null=True),
        ),
    ]
