# Generated by Django 3.2.4 on 2021-07-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_theme_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='theme_profile',
            field=models.CharField(blank=True, choices=[('', '------'), ('0', 'шарено'), ('1', 'синьо небе'), ('2', 'зелено'), ('3', 'лилаво'), ('4', 'слънчево')], default=1, max_length=20, null=True),
        ),
    ]
